### ISSUE TITLE
Implement Broadcasting

### ISSUE THREAD

**Issue by ValentinKaisermayer** [xKDR/TSx.jl#45] opened 2022-07-24 19:27 UTC
Since `apply` is really aggregation or downsampling it would be nice to supply some way of applying a function to a column which would keep the index intact. 

```julia
ts = TS(random(10))

sin.(ts[:x1]) .+ 2 
```
I think it is already possible with `rollapply` but this is kind of abusing the API
```julia
rollapply(x->sin(x) + 2, ts, :x1, 1)
```

**Comment by chiraganand** [comment] 2022-07-26 07:25
> Since `apply` is really aggregation or downsampling it would be nice to supply some way of applying a function to a column which would keep the index intact.

Do you mean you want to apply a function on a single column and return the entire `TS` object?

> ```julia
> ts = TS(random(10))
> 
> sin.(ts[:x1]) .+ 2 
> ```

Just FYI, this should be `sin.(ts[:, :x1]) .+ 2)`.

> I think it is already possible with `rollapply` but this is kind of abusing the API

Yes, I think it would be better to use `apply()` for column operations as well.

**Comment by ValentinKaisermayer** [comment] 2022-07-26 10:44
> Do you mean you want to apply a function on a single column and return the entire TS object?

Yes, it is sometimes useful to be able to do calculations directly. For instance if `ts` is a time series of temperature measurements in Kelvin but you want to plot it in Celsius.

> Just FYI, this should be sin.(ts[:, :x1]) .+ 2).

Can it be `ts.x1` ? If I want simply the whole column it is kind of verbose to write `ts[:, :x1]`. Which `DataFrames.jl` supports, and can be implemented via a `Base.getproperty` overload. 

https://github.com/JuliaData/DataFrames.jl/blob/14e682b623ccc07d34cb7399f79311e9443f9b13/src/abstractdataframe/abstractdataframe.jl#L401

**Comment by chiraganand** [comment] 2022-07-27 08:26
> > Do you mean you want to apply a function on a single column and return the entire TS object?
> 
> Yes, it is sometimes useful to be able to do calculations directly. For instance if `ts` is a time series of temperature measurements in Kelvin but you want to plot it in Celsius.

Got it, supplying column names would be useful in this case.

> 
> > Just FYI, this should be sin.(ts[:, :x1]) .+ 2).
> 
> Can it be `ts.x1` ? If I want simply the whole column it is kind of verbose to write `ts[:, :x1]`. Which `DataFrames.jl` supports, and can be implemented via a `Base.getproperty` overload.
> 
> https://github.com/JuliaData/DataFrames.jl/blob/14e682b623ccc07d34cb7399f79311e9443f9b13/src/abstractdataframe/abstractdataframe.jl#L401

Yes, good idea. Will create a separate issue for this.

**Comment by chiraganand** [comment] 2022-09-10 09:57
> > > Just FYI, this should be sin.(ts[:, :x1]) .+ 2).
> > 
> > 
> > Can it be `ts.x1` ? If I want simply the whole column it is kind of verbose to write `ts[:, :x1]`. Which `DataFrames.jl` supports, and can be implemented via a `Base.getproperty` overload.
> > https://github.com/JuliaData/DataFrames.jl/blob/14e682b623ccc07d34cb7399f79311e9443f9b13/src/abstractdataframe/abstractdataframe.jl#L401
> 
> Yes, good idea. Will create a separate issue for this.

Issue #70 is created for this feature.

**Comment by chiraganand** [comment] 2022-09-10 09:59
> > Do you mean you want to apply a function on a single column and return the entire TS object?
> 
> Yes, it is sometimes useful to be able to do calculations directly. For instance if `ts` is a time series of temperature measurements in Kelvin but you want to plot it in Celsius.

This feature is now tracked in #71.

**Comment by chiraganand** [comment] 2022-09-10 10:00
Marking this as duplicate of #26, let the discussion continue there.

**Closed by chiraganand** 2022-09-10 10:00 UTC
